### ISSUE TITLE
IsEqual does not support Array Types

### ISSUE THREAD

**Issue by robodude666** [VBA-tools/VBA-TDD#16]
IsEqual should support Array Types so that users can compare if two arrays are identical (same size, index 0 matches index 0, etc.). Currently it falls through to the else clause:

```
IsEqual = Actual = Expected
```

and causes a VB runtime error.

**Comment by timhall** [comment]
@vitosh actually sent a PR for this far too long ago, I'll merge that shortly to fix this.

**Comment by robodude666** [comment]
Ah, #12. I saw that some time ago but forgot about it.
