### ISSUE TITLE
SpecDefinition should return its own reference

### ISSUE THREAD

**Issue by robodude666** [VBA-tools/VBA-TDD#17]
It would be very helpful if `SpecDefinition` could return a reference to itself. For example:

```vb
With Specs.It("should be a good example")
    Set Foo = Bar.FooBarIt()
    VerifyIsAnObject(.Self, Foo)
End With

Private Function VerifyIsAnObject(ByRef SpecsIt As SpecDefinition, ByRef Foo As Bar)

    With SpecsIt
        .Expect(Foo...).ToBe...
    End With

End Function
```

While I understand RunMatcher exists, you may not want to make your various functions public. RunMatcher also doesn't support the fluent Expect().ToBe() syntax used throughout the rest of our suites.

**Comment by timhall** [comment]
Good idea, should be a quick fix, I'll try to get to this shortly.

**Comment by timhall** [comment]
Nearing a year on this and it's finally on the docket for changes for the [v2 change to vba-test](https://github.com/VBA-tools/VBA-TDD/pull/23)
